name: team_play
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-123.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  animate_do: ^3.0.2
  dio: ^5.2.1+1
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  google_sign_in: ^6.1.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_fonts: ^5.0.0
  firebase_core_platform_interface: ^4.8.0
  wave: ^0.2.2
  dartz: ^0.10.1
  geolocator: ^9.0.2
  formz: ^0.6.0
  dropdown_search: ^5.0.6
  flutter_map: ^5.0.0
  url_launcher: ^6.1.11
  latlong2: ^0.9.0
  tuple: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - .env
  fonts:
    - family: social_icons
      fonts:
        - asset: assets/icons/social_icons.ttf