// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyowJ0y4VKVqfnYhvChayJ7faNUZG2Csc',
    appId: '1:774350942563:web:92cbb9b2c68834d114a356',
    messagingSenderId: '774350942563',
    projectId: 'teamplay-2db94',
    authDomain: 'teamplay-2db94.firebaseapp.com',
    storageBucket: 'teamplay-2db94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLzmPZbazlieauzHJuNzTAlwhePcYz3Q',
    appId: '1:774350942563:android:c876ab24e36cbb3814a356',
    messagingSenderId: '774350942563',
    projectId: 'teamplay-2db94',
    storageBucket: 'teamplay-2db94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJq-IaC6CHMqT7qpXPmze5knsk5fa0rKY',
    appId: '1:774350942563:ios:1befaa80236122e114a356',
    messagingSenderId: '774350942563',
    projectId: 'teamplay-2db94',
    storageBucket: 'teamplay-2db94.appspot.com',
    androidClientId: '774350942563-l52a9a4blfp1k8ug3m3ib1std3s14ofa.apps.googleusercontent.com',
    iosClientId: '774350942563-7gjed6bnomm3tk8sj7d8uiuiqo49ndki.apps.googleusercontent.com',
    iosBundleId: 'app.g2.teamPlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJq-IaC6CHMqT7qpXPmze5knsk5fa0rKY',
    appId: '1:774350942563:ios:bb1dbda4031598a414a356',
    messagingSenderId: '774350942563',
    projectId: 'teamplay-2db94',
    storageBucket: 'teamplay-2db94.appspot.com',
    androidClientId: '774350942563-l52a9a4blfp1k8ug3m3ib1std3s14ofa.apps.googleusercontent.com',
    iosClientId: '774350942563-vdi7bt7s24ncfbvakhgbnhkq1ineaibn.apps.googleusercontent.com',
    iosBundleId: 'app.g2.teamPlay.RunnerTests',
  );
}
